# Generated by Django 3.0.5 on 2021-02-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_2011'),
        ('api', '0004_auto_20210219_2248'),
    ]

    operations = [
    ]