# Generated by Django 3.0.5 on 2021-02-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210222_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['role', '-email']},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
