# Generated by Django 3.0.5 on 2021-02-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210223_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Review', verbose_name='отзыв'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='отзыв'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['pub_date'], name='api_comment_pub_dat_dac963_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['review'], name='api_comment_review__7c04ce_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='api_comment_author__b4741e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['pub_date'], name='api_review_pub_dat_641af8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['title'], name='api_review_title_i_c7fb45_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author'], name='api_review_author__f3b77d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['score'], name='api_review_score_54e75f_idx'),
        ),
    ]
