# Generated by Django 3.0.5 on 2021-02-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210223_1859'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_review__7c04ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='api_review_title_i_c7fb45_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='api_review_author__f3b77d_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='api_genre_name_01c28c_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['name'], name='api_title_name_350714_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['year'], name='api_title_year_10c411_idx'),
        ),
    ]
