# Generated by Django 3.0.5 on 2021-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210224_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailauth',
            options={'verbose_name': 'запрос кода подтверждения', 'verbose_name_plural': 'запросы кода подтверждения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['role', '-email'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='emailauth',
            name='confirmation_code',
            field=models.CharField(max_length=32, verbose_name='код подтверждения'),
        ),
    ]
